### ISSUE TITLE
Include legal_form_code in response

### ISSUE THREAD

**Issue by landovsky** [redrick/registeruz#1]
It would greatly improve detection of general record type (právnická osoba / fyzická osoba) if the logic could be based on code than on text.

**Comment by redrick** [comment]
Yup, [done that couple weeks ago](https://github.com/redrick/registeruz/commit/25eaa8f8c9815259aedd6e9666ac72467e4f7568), but never found time to finish readme, will leave open until I do so...

Meantime I will leave here:

response now has `_id` for corresponding values taken from codebooks:
- legal_form
- sk_nace_code
- organization_size
- ownership_type
- region
- district
- residence

E.x.:
```ruby
subject.legal_form_id
=> 112

subject.legal_form
=> "Spol. s r. o."
```

**Comment by landovsky** [comment]
Well done :-). Thx.
